language: c++

matrix:
  include:
    # Clang on OSX
    # Sadly, OutputUHD still needs clock_gettime() even if UHD is available
    # in homebrew
    - env: MATRIX_EVAL="" CONF="--disable-output-uhd"
      os: osx
      osx_image: xcode9.1
      compiler: clang

    # GCC and clang builds on Linux
    - env: MATRIX_EVAL="CC=gcc-6 CXX=g++-6" CONF="--disable-zeromq --disable-output-uhd"
      os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      addons: &linuxaddons
        apt:
          sources: &sources
            - ubuntu-toolchain-r-test
          packages: &packages
            - libzmq3-dev
            - libzmq3
            - automake
            - libtool
            - libcurl4-openssl-dev
            - libfftw3-dev
            # libuhd-dev is not allowed
            - g++-6

    - env: MATRIX_EVAL="CC=gcc-6 CXX=g++-6" CONF="--disable-output-uhd --enable-output-raw"
      compiler: gcc
      addons: *linuxaddons

    - env: MATRIX_EVAL="CC=gcc-6 CXX=g++-6" CONF="--disable-output-uhd --disable-native"
      compiler: gcc
      addons: *linuxaddons

    - env: MATRIX_EVAL="CC=gcc-6 CXX=g++-6" CONF="--disable-output-uhd --enable-edi"
      compiler: gcc
      addons: *linuxaddons

    - env: MATRIX_EVAL="CC=gcc-6 CXX=g++-6" CONF="--disable-output-uhd --enable-trace"
      compiler: gcc
      addons: *linuxaddons

before_install:
  - eval "${MATRIX_EVAL}"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (brew install fftw zeromq automake || true); fi

script:
  - |
    ./bootstrap.sh
    ./configure $CONF
    make

